### ISSUE TITLE
RDOS support?

### ISSUE THREAD

**Issue by btb** [AppleCommander/AppleCommander#109]
I have a .dsk file which I believe is RDOS 3.3 formatted. diskm8 and CiderPress both seem to work with it but since I want to be able to script some interaction it would be much more convenient to use ac. Is this format missing and could it be added?

**Comment by btb** [comment]
Hmm, I searched for 'rdos' in the github ui and there were only a handful of vague hits, but I see now that RDOS images are indeed supposed to be supported, and there are some in the build tests that work. Are they an earlier version?

Here is one that doesn't: [RDOS_3.3_1986___RDOS.dsk.zip](https://github.com/AppleCommander/AppleCommander/files/12890105/RDOS_3.3_1986___RDOS.dsk.zip)

(from https://archive.org/details/a2_RDOS_3.3_1986__RDOS)

    $ diskm8 -with-disk RDOS_3.3_1986___RDOS.dsk -catalog
      __               __                  __    __     
     /\ \  __         /\ \      /'\_/`\  /'_ `\ /\ \    
     \_\ \/\_\    ____\ \ \/'\ /\      \/\ \L\ \\ \ \   
     /'_` \/\ \  /',__\\ \ , < \ \ \__\ \/_> _ <_\ \ \  
    /\ \L\ \ \ \/\__, `\\ \ \\`\\ \ \_/\ \/\ \L\ \\ \_\ 
    \ \___,_\ \_\/\____/ \ \_\ \_\ \_\\ \_\ \____/ \/\_\
     \/__,_ /\/_/\/___/   \/_/\/_/\/_/ \/_/\/___/   \/_/
                                                        
                                                        
    
    (c) 2015 - 2018 Paleotronic.com
    
    
    Volume Name is no-name
    
    NAME                               BLOCKS  RO  KIND                     ADDITONAL
    RDOS 3.3 COPYRIGHT 1986                33      Binary File              (A$1000)
    SYSTEMBOOT                              2      ASCII Text               
    MENU                                    3      Applesoft Basic Program  
    DISK UTILITY                            6      Applesoft Basic Program  
    DISK UTILITY.OBJ                        4      Binary File              (A$1000)
    INSTRUCTION SUMMARY                    25      Applesoft Basic Program  
    CHANGE HELLO PROGRAM                    1      Applesoft Basic Program  
    PLE                                     8      Applesoft Basic Program  
    
    USED: 79                   FREE: 481                 
    
    $ ac -i RDOS_3.3_1986___RDOS.dsk 
    Error: DiskUnrecognizedException
    com.webcodepro.applecommander.storage.DiskUnrecognizedException: DiskUnrecognizedException
	    at com.webcodepro.applecommander.storage.Disk.getFormattedDisks(Disk.java:410)
	    at com.webcodepro.applecommander.ui.ac.getDiskInfo(ac.java:548)
	    at com.webcodepro.applecommander.ui.ac.main(ac.java:120)
	    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	    at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	    at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	    at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	    at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
`
