### ISSUE TITLE
Import Wizard doesn't disable Edit button after removing item from list; crashes when clicked

### ISSUE THREAD

**Issue by ryandesign** [AppleCommander/AppleCommander#120]
With AppleCommander 1.8.0 on macOS Monterey I did this:

1. Create a new DOS disk image or open an existing one.
2. Click Import… in the toolbar.
3. In the Import Wizard, note that the Remove and Edit… buttons are disabled because there are no items yet.
4. Click Choose… and select any file. The Remove and Edit… buttons are still disabled because no items are selected.
6. Select the file you added. The Remove and Edit… buttons enable.
7. Click Remove. The file is removed, the Remove button disables, but the Edit… button remains enabled.
8. Click Edit…
9. AppleCommander crashes:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at com.webcodepro.applecommander.ui.swt.wizard.importfile.ImportSelectFilesWizardPane.editSelection(ImportSelectFilesWizardPane.java:279)
	at com.webcodepro.applecommander.ui.swt.wizard.importfile.ImportSelectFilesWizardPane$4.widgetSelected(ImportSelectFilesWizardPane.java:211)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4565)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1522)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1545)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1530)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4351)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3927)
	at com.webcodepro.applecommander.ui.swt.wizard.Wizard.open(Wizard.java:162)
	at com.webcodepro.applecommander.ui.swt.DiskExplorerTab.importFiles(DiskExplorerTab.java:1150)
	at com.webcodepro.applecommander.ui.swt.DiskExplorerTab$49.widgetSelected(DiskExplorerTab.java:1334)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4565)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1522)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1545)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1530)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4351)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3927)
	at com.webcodepro.applecommander.ui.swt.SwtAppleCommander.launch(SwtAppleCommander.java:118)
	at com.webcodepro.applecommander.ui.swt.SwtAppleCommander.launch(SwtAppleCommander.java:86)
	at com.webcodepro.applecommander.ui.swt.SwtAppleCommander.main(SwtAppleCommander.java:71)
	... 8 more
```

**Comment by ryandesign** [comment]
Thanks, 0bccdde28a5fe9084056ff79559604a29d61502d fixes it.
