### ISSUE TITLE
GUI does not start on macOS High Sierra

### ISSUE THREAD

**Issue by sduensin** [AppleCommander/AppleCommander#26]
$ java -jar AppleCommander-macosx-1.4.0.jar
***WARNING: Display must be created on main thread due to Cocoa restrictions.
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.webcodepro.applecommander.ui.AppleCommander.launchSwtAppleCommander(AppleCommander.java:101)
	at com.webcodepro.applecommander.ui.AppleCommander.main(AppleCommander.java:56)
Caused by: org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.widgets.Display.error(Unknown Source)
	at org.eclipse.swt.widgets.Display.createDisplay(Unknown Source)
	at org.eclipse.swt.widgets.Display.create(Unknown Source)
	at org.eclipse.swt.graphics.Device.<init>(Unknown Source)
	at org.eclipse.swt.widgets.Display.<init>(Unknown Source)
	at org.eclipse.swt.widgets.Display.<init>(Unknown Source)
	at com.webcodepro.applecommander.ui.swt.SwtAppleCommander.launch(SwtAppleCommander.java:77)
	... 6 more

$ java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

**Comment by a2geek** [comment]
Hey @sduensin, I agree that's confusing.  Can you try this instead? 

```
java -XstartOnFirstThread -jar AppleCommander-macosx-1.4.0.jar
```

 It's a requirement of SWT.  I see the docs sort of munge that a bit.

**Comment by sduensin** [comment]
That did it!  Thanks!

**Comment by a2geek** [comment]
Great! If you think there is some tweaks to https://applecommander.github.io/ that should be done, please let me know. Or, even better yet, just submit a pull request!
