### ISSUE TITLE
AppleCommander-macosx-1.5.0.jar dies

### ISSUE THREAD

**Issue by quentinnuk** [AppleCommander/AppleCommander#37]
Hi

Im trying to run AppleCommander-macosx-1.5.0.jar on my Mac but it just dies on launch. I assume Im doing something wrong here, but Im not a java person. MacOS 10.13.6 and Java 1.8.0_221-b11:

$ java -jar AppleCommander-macosx-1.5.0.jar 
***WARNING: Display must be created on main thread due to Cocoa restrictions.
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.webcodepro.applecommander.ui.AppleCommander.launchSwtAppleCommander(AppleCommander.java:101)
	at com.webcodepro.applecommander.ui.AppleCommander.main(AppleCommander.java:56)
Caused by: org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.widgets.Display.error(Unknown Source)
	at org.eclipse.swt.widgets.Display.createDisplay(Unknown Source)
	at org.eclipse.swt.widgets.Display.create(Unknown Source)
	at org.eclipse.swt.graphics.Device.<init>(Unknown Source)
	at org.eclipse.swt.widgets.Display.<init>(Unknown Source)
	at org.eclipse.swt.widgets.Display.<init>(Unknown Source)
	at com.webcodepro.applecommander.ui.swt.SwtAppleCommander.launch(SwtAppleCommander.java:77)
	... 6 more

**Comment by a2geek** [comment]
The Mac requires an extra flag. Hopefully this is all that's needed!
```
$ java -XstartOnFirstThread -jar AppleCommander-macosx-1.5.0.jar
```

**Comment by quentinnuk** [comment]
Yes that worked. Thanks. Maybe it would be possible to build a .app executable for this to make it a bit more straight forward for less technical folks.

**Comment by lifepillar** [comment]
@quentinnuk If you use [Homebrew](https://brew.sh/), you may like [homebrew-appleii](https://github.com/lifepillar/homebrew-appleii). Then, this and several other Apple ][ goodies become easily available. For AppleCommander:

```
brew install applecommander
applecommander-gui
```

**Comment by quentinnuk** [comment]
THanks. I still use macports, but Ill have a look at homebrew-appleII
