### ISSUE TITLE
Return result code?

### ISSUE THREAD

**Issue by savetz** [AppleCommander/AppleCommander#44]
Is it possible for AppleCommander to give a return a code for a failed BASIC parse?

I call it with 
    result = os.system('java -jar ac.jar -bas ...etc...

If I give try to import something that isn't code, it shows:

Error: Expected a number in line #1
java.lang.RuntimeException: Expected a number in line #1
	at io.github.applecommander.bastools.api.Parser.expectNumber(Parser.java:68)
	at io.github.applecommander.bastools.api.Parser.readLine(Parser.java:34)
	at io.github.applecommander.bastools.api.Parser.parse(Parser.java:28)
	at com.webcodepro.applecommander.ui.ac.putAppleSoft(ac.java:198)
	at com.webcodepro.applecommander.ui.ac.main(ac.java:175)
AppleCommander command line options [1.6.0]:
-i       <imagename> [<imagename>] display information about image(s).
...etc...

BUT it doesn't return a result of 256 to my calling program, so my script doesn't know that it failed.

Is this fixable?

Thanks.
Kay

**Comment by a2geek** [comment]
I think that's a great idea. And easy!

I took out the extra help as well. Thought it might hide the error message (the stack trace is messy enough).

```
$ echo "print 'hello'" | ac -bas deleteme.po whut
Error: Expected a number in line #1
java.lang.RuntimeException: Expected a number in line #1
	at io.github.applecommander.bastools.api.Parser.expectNumber(Parser.java:68)
	at io.github.applecommander.bastools.api.Parser.readLine(Parser.java:34)
	at io.github.applecommander.bastools.api.Parser.parse(Parser.java:28)
	at com.webcodepro.applecommander.ui.ac.putAppleSoft(ac.java:198)
	at com.webcodepro.applecommander.ui.ac.main(ac.java:175)
$ echo $?
1
```
