### ISSUE TITLE
Won't start with MacOS Catalina (10.15.7)

### ISSUE THREAD

**Issue by WizardOfWor1969** [AppleCommander/AppleCommander#46]
Any help is appreciated. If you need more information, let me know. 

From the terminal:

java -jar AppleCommander-macosx-1.6.0.jar 
***WARNING: Display must be created on main thread due to Cocoa restrictions.
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.webcodepro.applecommander.ui.AppleCommander.launchSwtAppleCommander(AppleCommander.java:103)
	at com.webcodepro.applecommander.ui.AppleCommander.main(AppleCommander.java:57)
Caused by: org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.widgets.Display.error(Unknown Source)
	at org.eclipse.swt.widgets.Display.createDisplay(Unknown Source)
	at org.eclipse.swt.widgets.Display.create(Unknown Source)
	at org.eclipse.swt.graphics.Device.<init>(Unknown Source)
	at org.eclipse.swt.widgets.Display.<init>(Unknown Source)
	at org.eclipse.swt.widgets.Display.<init>(Unknown Source)
	at com.webcodepro.applecommander.ui.swt.SwtAppleCommander.launch(SwtAppleCommander.java:78)
	... 6 more

**Comment by lifepillar** [comment]
If you install it with Homebrew, using my [Homebrew repo](https://github.com/lifepillar/homebrew-appleii), it should work. I think that it's launched with `-XstartOnFirstThread`, but you may browse [the source code of the formula](https://github.com/lifepillar/homebrew-appleii/blob/master/Formula/applecommander.rb).

**Comment by WizardOfWor1969** [comment]
Thanks, I don't want to have to install homebrew just to run the app. I did try your suggestion of using -XstartOnFirstThread, that launches the program. So , thanks! Now it won't open any files (see screenshot). Possible problem with MacOS security? I was never prompted for permission to access files in a directory, which I occasionally see with other programs.

![Screen Shot 2020-10-07 at 1 55 46 PM](https://user-images.githubusercontent.com/52321250/95387017-04e9f680-08a5-11eb-98b8-f17d3c049f85.jpg)

**Comment by WizardOfWor1969** [comment]
Never mind. If I select open all files from that drop down that says 140K DOS Ordered Images (*.do, *.dsk), it will open. This is of course wrong, as the selection above SHOULD work too.

**Comment by a2geek** [comment]
There is a note on the web site regarding the `-XstartOnFirstThread` being required as well, in case that helps: https://applecommander.github.io/install/#graphical-interface

**Comment by a2geek** [comment]
I am curious about the GUI not recognizing the files based on the filter... there was some finagling that had to be done for Windows (#35) so there may be something with the Mac as well.
