### ISSUE TITLE
AppleCommander SWT GUI crashes with a NullPointerException after selection of file from open dialog

### ISSUE THREAD

**Issue by a2geek** [AppleCommander/AppleCommander#49]
This may be something related to the internals of SWT itself?

```
% java -XstartOnFirstThread -jar build/libs/AppleCommander-macosx-1.7.0pre.jar
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.webcodepro.applecommander.ui.AppleCommander.launchSwtAppleCommander(AppleCommander.java:103)
	at com.webcodepro.applecommander.ui.AppleCommander.main(AppleCommander.java:57)
Caused by: java.lang.NullPointerException
	at org.eclipse.swt.widgets.Control.internal_new_GC(Unknown Source)
	at org.eclipse.swt.graphics.GC.<init>(Unknown Source)
	at org.eclipse.swt.graphics.GC.<init>(Unknown Source)
	at org.eclipse.swt.custom.CTabFolder.updateTabHeight(Unknown Source)
	at org.eclipse.swt.custom.CTabFolder.runUpdate(Unknown Source)
	at org.eclipse.swt.custom.CTabItem.getBounds(Unknown Source)
	at org.eclipse.swt.custom.CTabFolder.onPaint(Unknown Source)
	at org.eclipse.swt.custom.CTabFolder$1.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Control.drawWidget(Unknown Source)
	at org.eclipse.swt.widgets.Widget.drawRect(Unknown Source)
	at org.eclipse.swt.widgets.Display.windowProc(Unknown Source)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationNextEventMatchingMask(Unknown Source)
	at org.eclipse.swt.widgets.Display.applicationProc(Unknown Source)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.nextEventMatchingMask(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at com.webcodepro.applecommander.ui.swt.SwtAppleCommander.launch(SwtAppleCommander.java:93)
	at com.webcodepro.applecommander.ui.swt.SwtAppleCommander.launch(SwtAppleCommander.java:79)
	... 6 more
```

**Comment by a2geek** [comment]
There seem to be many references to this type of stack trace across multiple versions of SWT. For instance: https://bugs.eclipse.org/bugs/show_bug.cgi?id=548430
