### ISSUE TITLE
Can't launch AppleCommander on Windows 10

### ISSUE THREAD

**Issue by djcarlin** [AppleCommander/AppleCommander#52]
I can't launch AppleCommander on Windows 10.

Fresh install of Windows 10 Pro version 20H2 OS build 19042.685

Fresh install of Java Version 8 Update 271 (build 1.8.0_271-b09)

When you double click on AppleCommander-win64-1.6.0.jar nothing happens.  If I right click and Open nothing happens.  I then tried opening via Command Prompt and saw this:

C:\Users\David\Downloads>java -jar AppleCommander-win64-1.6.0.jar
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.webcodepro.applecommander.ui.AppleCommander.launchSwtAppleCommander(AppleCommander.java:103)
        at com.webcodepro.applecommander.ui.AppleCommander.main(AppleCommander.java:57)
Caused by: java.lang.UnsatisfiedLinkError: Cannot load 64-bit SWT libraries on 32-bit JVM
        at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
        at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
        at org.eclipse.swt.internal.C.<clinit>(Unknown Source)
        at org.eclipse.swt.widgets.Display.<clinit>(Unknown Source)
        at com.webcodepro.applecommander.ui.swt.SwtAppleCommander.launch(SwtAppleCommander.java:78)
        ... 6 more

**Comment by a2geek** [comment]
Hey @djcarlin - From the message `Cannot load 64-bit SWT libraries on 32-bit JVM`, it looks like you have a 32 bit version of Java installed. Can you try with the 64-bit version?

For what it's worth, you can use `java -version` to see what is installed:
```
$ java -version
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)
```
(Yeah, Linux, but the principal still applies!)

**Comment by djcarlin** [comment]
Thank you, that worked.  Java.com "Java Download" button defaults to 32-bit
