### ISSUE TITLE
Mac version does not run GUI on Apple silicon

### ISSUE THREAD

**Issue by a2geek** [AppleCommander/AppleCommander#62]
Need to see if a SWT variant arm64 exists.

```
 % java -jar ~/Downloads/AppleCommander-macosx-1.6.0.jar 
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.webcodepro.applecommander.ui.AppleCommander.launchSwtAppleCommander(AppleCommander.java:103)
	at com.webcodepro.applecommander.ui.AppleCommander.main(AppleCommander.java:57)
Caused by: java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-cocoa-4626 in java.library.path: [/Users/rob/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
	no swt-cocoa in java.library.path: [/Users/rob/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
	Can't load library: /Users/rob/.swt/lib/macosx/aarch64/libswt-cocoa-4626.jnilib
	Can't load library: /Users/rob/.swt/lib/macosx/aarch64/libswt-cocoa.jnilib
	/Users/rob/.swt/lib/macosx/aarch64/libswt-cocoa-4626.jnilib: dlopen(/Users/rob/.swt/lib/macosx/aarch64/libswt-cocoa-4626.jnilib, 0x0001): tried: '/Users/rob/.swt/lib/macosx/aarch64/libswt-cocoa-4626.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/libswt-cocoa-4626.jnilib' (no such file), '/usr/lib/libswt-cocoa-4626.jnilib' (no such file)

	at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
	at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
	at org.eclipse.swt.internal.C.<clinit>(Unknown Source)
	at org.eclipse.swt.widgets.Display.<clinit>(Unknown Source)
	at com.webcodepro.applecommander.ui.swt.SwtAppleCommander.launch(SwtAppleCommander.java:78)
	... 6 more
```

**Comment by a2geek** [comment]
Noting that current versions of SWT are built for aarch64 (aka Apple Silicon):
* https://download.eclipse.org/eclipse/downloads/drops4/R-4.22-202111241800/

This is also available in Maven (the versions don't match but the `version.txt` file indicates they are the same:
* https://mvnrepository.com/artifact/org.eclipse.platform/org.eclipse.swt.cocoa.macosx.aarch64
