### ISSUE TITLE
Not an AppleSingle file - magic number does not match.

### ISSUE THREAD

**Issue by nilseuropa** [AppleCommander/AppleCommander#74]
Hi, 

I have AppleCommander v1.7.0 and cc65 v2.19 installed.

When I try to put cc65 compiled binary to a disk image with `-as` I get the following error message:

```
Error: Not an AppleSingle file - magic number does not match.  Expected 0x00051600 but read 0x3b0a3b20.
java.io.IOException: Not an AppleSingle file - magic number does not match.  Expected 0x00051600 but read 0x3b0a3b20.
	at io.github.applecommander.applesingle.AppleSingle.required(AppleSingle.java:201)
	at io.github.applecommander.applesingle.AppleSingle.asEntries(AppleSingle.java:181)
	at io.github.applecommander.applesingle.AppleSingle.asEntries(AppleSingle.java:176)
	at io.github.applecommander.applesingle.AppleSingle.read(AppleSingle.java:159)
	at io.github.applecommander.applesingle.AppleSingle.read(AppleSingle.java:147)
	at com.webcodepro.applecommander.ui.ac.putAppleSingle(ac.java:374)
	at com.webcodepro.applecommander.ui.ac.putAppleSingle(ac.java:366)
	at com.webcodepro.applecommander.ui.ac.main(ac.java:168)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
```

**Comment by nilseuropa** [comment]
The issue disappears if I omit the `bin` argument.

**Comment by a2geek** [comment]
If you can, it would be useful to get a quick summary of what was going on. I'm uncertain what you mean by the `bin` argument, and my guess is someone else may run into the same problem. If there is anything that can be updated in documentation, that would be good to know as well. Thanks!

**Comment by nilseuropa** [comment]
Test case

`cl65 -t apple2 -Ois -m hello.map hello.c -o hello.apple2`

This is throwing an exception:
`ac.sh -as hello.dsk hello bin < hello.apple2`

And this is not:
`ac.sh -as hello.dsk hello < hello.apple2`

Probably because of the AppleSingle meta already has everything necessary and I've confused AC with the `bin` argument (?)
