### ISSUE TITLE
Doesnt' work on my Apple MacMini M1

### ISSUE THREAD

**Issue by aminta** [AppleCommander/AppleCommander#83]
Hi, I get the error when I launch `java -jar AppleCommander-macosx-aarch64-1.7.0.jar`:

```
***WARNING: Display must be created on main thread due to Cocoa restrictions. Use vmarg -XstartOnFirstThread
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4907)
	at org.eclipse.swt.SWT.error(SWT.java:4822)
	at org.eclipse.swt.SWT.error(SWT.java:4793)
	at org.eclipse.swt.widgets.Display.error(Display.java:1148)
	at org.eclipse.swt.widgets.Display.createDisplay(Display.java:899)
	at org.eclipse.swt.widgets.Display.create(Display.java:883)
	at org.eclipse.swt.graphics.Device.<init>(Device.java:131)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:739)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:730)
	at com.webcodepro.applecommander.ui.swt.SwtAppleCommander.launch(SwtAppleCommander.java:80)
	at com.webcodepro.applecommander.ui.swt.SwtAppleCommander.main(SwtAppleCommander.java:71)
	... 6 more
```

I'm on Monterey 12.3.1, MacMini M1, Java version:

```
openjdk version "18" 2022-03-22
OpenJDK Runtime Environment Zulu18.28+13-CA (build 18+37)
OpenJDK 64-Bit Server VM Zulu18.28+13-CA (build 18+37, mixed mode, sharing)
```

**Comment by a2geek** [comment]
On the Mac you need to use `-XstartOnFirstThread`.  It's not entirely clear, unfortunately.

Something like this (it's semi buried [in the docs](https://applecommander.github.io/install/#graphical-interface)):
```
#!/bin/sh
java -XstartOnFirstThread -jar ~/bin/AppleCommander-macosx-VERSION.jar
```

**Comment by aminta** [comment]
> On the Mac you need to use `-XstartOnFirstThread`. It's not entirely clear, unfortunately.
> 
> Something like this (it's semi buried [in the docs](https://applecommander.github.io/install/#graphical-interface)):
> 
> ```
> #!/bin/sh
> java -XstartOnFirstThread -jar ~/bin/AppleCommander-macosx-VERSION.jar
> ```

It works, thanks!

**Comment by a2geek** [comment]
Good to hear!
