### ISSUE TITLE
Crash when resizing main window

### ISSUE THREAD

**Issue by swinslow** [AppleCommander/AppleCommander#89]
After opening a disk image for inspection in the AppleCommander GUI, the file view opened correctly. But when dragging the lower-right corner to resize the window, the program crashed with the crash log text below. Happy to provide more details if helpful!

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.IllegalArgumentException: Argument not valid
	at org.eclipse.swt.SWT.error(SWT.java:4888)
	at org.eclipse.swt.SWT.error(SWT.java:4822)
	at org.eclipse.swt.SWT.error(SWT.java:4793)
	at org.eclipse.swt.graphics.Image.init(Image.java:1370)
	at org.eclipse.swt.graphics.Image.<init>(Image.java:538)
	at com.webcodepro.applecommander.ui.swt.DiskMapTab.paintDiskMap(DiskMapTab.java:301)
	at com.webcodepro.applecommander.ui.swt.DiskMapTab.paintBlockMap(DiskMapTab.java:279)
	at com.webcodepro.applecommander.ui.swt.DiskMapTab.paintMap(DiskMapTab.java:205)
	at com.webcodepro.applecommander.ui.swt.DiskMapTab$3.paintControl(DiskMapTab.java:139)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:234)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4565)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1522)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1545)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1530)
	at org.eclipse.swt.widgets.Control.drawWidget(Control.java:1270)
	at org.eclipse.swt.widgets.Canvas.drawWidget(Canvas.java:176)
	at org.eclipse.swt.widgets.Widget.drawRect(Widget.java:776)
	at org.eclipse.swt.widgets.Canvas.drawRect(Canvas.java:170)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6200)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationNextEventMatchingMask(Display.java:5474)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5878)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:235)
	at org.eclipse.swt.widgets.Widget.windowSendEvent(Widget.java:2160)
	at org.eclipse.swt.widgets.Shell.windowSendEvent(Shell.java:2487)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6357)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationSendEvent(Display.java:5601)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5744)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.sendEvent(NSApplication.java:117)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3924)
	at com.webcodepro.applecommander.ui.swt.SwtAppleCommander.launch(SwtAppleCommander.java:118)
	at com.webcodepro.applecommander.ui.swt.SwtAppleCommander.launch(SwtAppleCommander.java:86)
	at com.webcodepro.applecommander.ui.swt.SwtAppleCommander.main(SwtAppleCommander.java:71)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 5 more
```

**Comment by swinslow** [comment]
Apologies, I should have noted: This was for the AppleCommander 1.8.0 release, aarch64, on Mac OS X Monterey 12.6, with OpenJDK 19 installed via Homebrew.

**Comment by ryandesign** [comment]
I can confirm this crash with AppleCommander 1.8.0 x86_64 on macOS Monterey 12.6.8 with openjdk 11.0.20.1 using MacPorts.

The crash only seems to happen if the window height is decreased. I don't get a crash if I increase the height or if I increase or decrease the width.

Also, if I switch to the Disk Map tab first, then the crash does not occur, even if I subsequently switch to other tabs.

**Comment by a2geek** [comment]
Sorry it's taken me so long to even try this. I can't replicate it. I tried with 1.8.0 and various disk types (ProDOS 140K/HDD, Pascal, DOS 3.3). I see it's in the disk map, so I tried on that tab as well and got nothing. I have a Mac M1 also using Homebrew Java 11.

I have updated the SWT libraries to the latest I can use for Java 11. So, an AppleCommander 1.9 snapshot build might be useful to try as well (hoping it was something in the windowing toolkit that was at fault). Snapshot builds are in the Github actions tab. The most current one right now is here: https://github.com/AppleCommander/AppleCommander/actions/runs/6671428863 -- look for "build-artifacts" and it will download a Zip file of all AppleCommander versions (including both Mac OS X versions of course).

**Comment by ryandesign** [comment]
The issue is reproducible 100% of the time on macOS even with the latest 1.9.0 snapshot.

Open AppleCommander GUI. Click Open… and select a disk image or click Create… to make a new one. Decrease the height of the window that opens. Crash.

If I switch to the Disk Map tab first, the crash is avoided.

I also do not see the problem if I pass a disk filename to AppleCommander when launching the GUI from the command line. I only see the problem if the disk window opens via the Open… or Create… toolbar buttons.

The mention of `DiskMapTab` and `paint` in the traceback makes me wonder: *should* the disk map tab be painting anything when it is not shown? If yes, then I suspect the problem is that something is not initialized until the tab is shown.

**Comment by a2geek** [comment]
This is crazy since I can't recreate this on my Mac! I poked through the code referenced in the stack trace and I did make a patch -- I think I'm seeing the impacted area is 0 for either or both height and width. The build artifact is here: https://github.com/AppleCommander/AppleCommander/actions/runs/6726052001

**Comment by ryandesign** [comment]
Thanks! That fixes the crash for me.
